language: python
python: 3.5

# Branch whitelist
branches:
    only:
        - master
        - develop

install: pip install -r "requirements.txt"

script:
    - coverage run --source . -m py.test && coverage report --skip-covered --fail-under 95
