language: python
python: 3.5

# Branch whitelist
branches:
    only:
        - master
        - develop

before_install:
    - rvm install 2.3.1
install:
    - pip install -r "requirements.txt"
    - gem install bundler && bundle install
script:
    - coverage run --source . -m py.test && coverage report --skip-covered --fail-under 95
    - bundle exec danger
